<?php

/**
 * Implementation of hook_theme()
 */
function progress_tracker_theme() {
  return array(
    'progress_tracker' => array(
      'template' => 'progress-tracker',
      'arguments' => array('steps' => null),
    ),
    'progress_tracker_item' => array(
      'template' => 'progress-tracker-item',
      'arguments' => array('step_text' => null),
    ),
  );
}

/**
 * Implementation of hook_block()
 */
function progress_tracker_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Progress Tracker'),
      'cache' => BLOCK_NO_CACHE,
    );

    return $blocks;
  }
  else if ($op == 'configure' && $delta == 0) {
    $form['steps'] = array(
      '#type' => 'textarea',
      '#title' => t('Progress tracker steps'),
      '#default_value' => variable_get('progress_tracker_steps', ''),
      '#description' => t('Enter progress bar steps as "url|step text" e.g <br>cart/checkout|Step 1 Billing & Payment<br>cart/review|Step 2 Review Order<br>cart/confirm|Step 3 Order Confirmation'),
    );
    $form['layout'] = array(
      '#type' => 'radios',
      '#title' => t('Progress Tracker Layout'),
      '#default_value' => variable_get('progress_tracker_layout', 'horizontal'),
      '#description' => t('Select horizontal or vertical layout for progress tracker.'),
      '#options' => array('horizontal' => t('Horizontal'), 'vertical' => t('Vertical')),
    );
    return $form;
  }
  else if ($op == 'save' && $delta == 0) {
    variable_set('progress_tracker_steps', $edit['steps']);
    variable_set('progress_tracker_layout', $edit['layout']);
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => t('Progress Tracker'),
          'content' => _progress_tracker(),
        );
        break;
    }
    return $block;
  }
}

function _progress_tracker() {
  $steps = variable_get('progress_tracker_steps', '');
  $steps = explode(chr(13), $steps);

  //add css file
  $path = drupal_get_path('module', 'progress_tracker');
  drupal_add_css($path . '/css/progress_tracker.css');

  $items = array();
  $cur_url = arg();
  foreach ($steps as $step_number => $step) {
    $step_arr = explode('|', $step);
    $selected_class = '';
    if (implode('/', $cur_url) == trim($step_arr[0])) {
      $selected_class = 'selected';
    }
    else {
      $selected_class = '';
    }
    $items[] = array('data' => theme('progress_tracker_item', $step_arr[1]), 'class' => $selected_class);
  }
  $output = '';
  if (count($items)) {
    $output = theme('item_list', $items, null, 'ul', array('class' => 'progress-tracker '.variable_get('progress_tracker_layout', 'horizontal')));
  }
  return theme('progress_tracker', $output);
}
