<?php

function shopping_cart_views_product_slider_view() {
$view = new view;
$view->name = 'business_card_product_slider';
$view->description = 'Business Card Product Slider';
$view->tag = '';
$view->base_table = 'node';
$view->core = 6;
$view->api_version = '2';
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
$handler = $view->new_display('default', 'Image Slider', 'default');
$handler->override_option('fields', array(
  'view_node' => array(
    'label' => '',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'absolute' => 0,
      'link_class' => '',
      'alt' => '',
      'rel' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'text' => '',
    'exclude' => 0,
    'id' => 'view_node',
    'table' => 'node',
    'field' => 'view_node',
    'relationship' => 'none',
  ),
  'field_image_upload_fid' => array(
    'label' => 'Image Upload',
    'alter' => array(
      'alter_text' => 1,
      'text' => '<img src="[field_image_upload_fid]" /> ',
      'make_link' => 0,
      'path' => '',
      'absolute' => 0,
      'link_class' => '',
      'alt' => '',
      'rel' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'hide_alter_empty' => 1,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'image_plain',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_image_upload_fid',
    'table' => 'node_data_field_image_upload',
    'field' => 'field_image_upload_fid',
    'relationship' => 'none',
  ),
  'field_image_upload_fid_1' => array(
    'id' => 'field_image_upload_fid_1',
    'table' => 'node_data_field_image_upload',
    'field' => 'field_image_upload_fid',
  ),
));
$handler->override_option('arguments', array(
  'tid' => array(
    'default_action' => 'default',
    'style_plugin' => 'default_summary',
    'style_options' => array(),
    'wildcard' => 'all',
    'wildcard_substitution' => 'All',
    'title' => '',
    'breadcrumb' => '',
    'default_argument_type' => 'php',
    'default_argument' => '',
    'validate_type' => 'none',
    'validate_fail' => 'not found',
    'break_phrase' => 1,
    'add_table' => 0,
    'require_value' => 0,
    'reduce_duplicates' => 0,
    'set_breadcrumb' => 0,
    'id' => 'tid',
    'table' => 'term_node',
    'field' => 'tid',
    'validate_user_argument_type' => 'uid',
    'validate_user_roles' => array(
      2 => 0,
    ),
    'relationship' => 'none',
    'default_options_div_prefix' => '',
    'default_taxonomy_tid_term_page' => 0,
    'default_taxonomy_tid_node' => 0,
    'default_taxonomy_tid_limit' => 0,
    'default_taxonomy_tid_vids' => array(
      2 => 0,
      1 => 0,
    ),
    'default_argument_user' => 0,
    'default_argument_fixed' => '',
    'default_argument_php' => '// Get the vocabulary tree information.
$alias = drupal_get_path_alias($_GET[\'q\']);
$path = explode("/",$alias);
$tids = array();
$node = array();
if(isset($path[3])){
        $term = taxonomy_get_term_by_name(str_replace("-"," ",$path[3]));
	$tids[] = $term[0]->tid;
	$list_term = taxonomy_select_nodes($tids);
		
	while($row = db_fetch_object($list_term)) {
          $node[] = $row->nid;
        }
}

$nids = implod("+",$node);
watchdog("test",$nids);
return $nids ;',
    'validate_argument_node_type' => array(
      'blog' => 0,
      'poll' => 0,
      'announcements' => 0,
      'product' => 0,
      'backlit_duratran' => 0,
      'booklets' => 0,
      'brochures' => 0,
      'business_cards' => 0,
      'cd_dvd_inserts' => 0,
      'event_tickets' => 0,
      'flyers' => 0,
      'folders' => 0,
      'menus' => 0,
      'newsletters' => 0,
      'postcards' => 0,
      'posters' => 0,
      'rack_cards' => 0,
      'sell_sheets' => 0,
      'vinyl_banners' => 0,
      'yard_signs' => 0,
      'product_kit' => 0,
      'forum' => 0,
      'featured_slider' => 0,
      'image_slider' => 0,
      'page' => 0,
      'templates' => 0,
    ),
    'validate_argument_node_access' => 0,
    'validate_argument_nid_type' => 'nid',
    'validate_argument_vocabulary' => array(
      2 => 0,
      1 => 0,
    ),
    'validate_argument_type' => 'tid',
    'validate_argument_transform' => 0,
    'validate_user_restrict_roles' => 0,
    'validate_argument_php' => '',
  ),
));
$handler->override_option('filters', array(
  'type' => array(
    'operator' => 'in',
    'value' => array(
      'image_slider' => 'image_slider',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'relationship' => 'none',
  ),
  'status' => array(
    'operator' => '=',
    'value' => '1',
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'status',
    'table' => 'node',
    'field' => 'status',
    'relationship' => 'none',
  ),
));
$handler->override_option('access', array(
  'type' => 'none',
));
$handler->override_option('cache', array(
  'type' => 'none',
));
$handler->override_option('style_plugin', 'views_nivo_slider');
$handler->override_option('style_options', array(
  'imagefield_preset' => 'full-size',
  'style' => 'default',
  'effect' => 'random',
  'slices' => '15',
  'animSpeed' => '500',
  'pauseTime' => '3000',
  'directionNav' => 'true',
  'directionNavHide' => 'true',
  'controlNav' => 'basic',
  'controlNavThumbsIC' => 'full-size',
  'controlNavThumbsICField' => '',
  'controlNavThumbsField' => 'title',
  'keyboardNav' => 'true',
  'pauseOnHover' => 'true',
  'manualAdvance' => 'false',
  'captionOpacity' => '0.8',
));
$handler->override_option('row_plugin', 'nivo_sliderfields');
$handler->override_option('row_options', array(
  'image_field' => 'field_image_upload_fid',
  'title_field' => 'title',
  'link_field' => 'view_node',
));
$handler = $view->new_display('block', 'Block', 'block_1');
$handler->override_option('fields', array(
  'view_node' => array(
    'label' => '',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'absolute' => 0,
      'link_class' => '',
      'alt' => '',
      'rel' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'text' => '',
    'exclude' => 0,
    'id' => 'view_node',
    'table' => 'node',
    'field' => 'view_node',
    'relationship' => 'none',
  ),
  'field_slider_image_fid' => array(
    'label' => 'Slider Image',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'absolute' => 0,
      'link_class' => '',
      'alt' => '',
      'rel' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'hide_alter_empty' => 1,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'image_plain',
    'multiple' => array(
      'group' => 1,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => 0,
    ),
    'exclude' => 0,
    'id' => 'field_slider_image_fid',
    'table' => 'node_data_field_slider_image',
    'field' => 'field_slider_image_fid',
    'override' => array(
      'button' => 'Use default',
    ),
    'relationship' => 'none',
  ),
));
$handler->override_option('arguments', array(
  'nid' => array(
    'default_action' => 'default',
    'style_plugin' => 'default_summary',
    'style_options' => array(),
    'wildcard' => 'all',
    'wildcard_substitution' => 'All',
    'title' => '',
    'breadcrumb' => '',
    'default_argument_type' => 'php',
    'default_argument' => '',
    'validate_type' => 'none',
    'validate_fail' => 'not found',
    'break_phrase' => 1,
    'not' => 0,
    'id' => 'nid',
    'table' => 'node',
    'field' => 'nid',
    'validate_user_argument_type' => 'uid',
    'validate_user_roles' => array(
      2 => 0,
    ),
    'override' => array(
      'button' => 'Use default',
    ),
    'relationship' => 'none',
    'default_options_div_prefix' => '',
    'default_taxonomy_tid_term_page' => 0,
    'default_taxonomy_tid_node' => 0,
    'default_taxonomy_tid_limit' => 0,
    'default_taxonomy_tid_vids' => array(
      2 => 0,
      1 => 0,
    ),
    'default_argument_user' => 0,
    'default_argument_fixed' => '',
    'default_argument_php' => '// Get the vocabulary tree information.
$alias = drupal_get_path_alias($_GET[\'q\']);
$path = explode("/",$alias);
$tids = array();
$nodeIds = array();
if(isset($path[3])){
        $term = taxonomy_get_term_by_name(str_replace("-"," ",$path[3]));
	$tids[] = $term[0]->tid;
	$list_term = taxonomy_select_nodes($tids);
		
	while($row = db_fetch_object($list_term)) {
          $nodeIds [] = $row->nid;
        }
}

$nids = implode(\'+\',$nodeIds );

return $nids ;',
    'validate_argument_node_type' => array(
      'blog' => 0,
      'poll' => 0,
      'announcements' => 0,
      'product' => 0,
      'backlit_duratran' => 0,
      'booklets' => 0,
      'brochures' => 0,
      'business_cards' => 0,
      'cd_dvd_inserts' => 0,
      'event_tickets' => 0,
      'flyers' => 0,
      'folders' => 0,
      'menus' => 0,
      'newsletters' => 0,
      'postcards' => 0,
      'posters' => 0,
      'rack_cards' => 0,
      'sell_sheets' => 0,
      'vinyl_banners' => 0,
      'yard_signs' => 0,
      'product_kit' => 0,
      'forum' => 0,
      'featured_slider' => 0,
      'image_slider' => 0,
      'page' => 0,
      'templates' => 0,
    ),
    'validate_argument_node_access' => 0,
    'validate_argument_nid_type' => 'nid',
    'validate_argument_vocabulary' => array(
      2 => 0,
      1 => 0,
    ),
    'validate_argument_type' => 'tid',
    'validate_argument_transform' => 0,
    'validate_user_restrict_roles' => 0,
    'validate_argument_php' => '',
  ),
));
$handler->override_option('filters', array(
  'type' => array(
    'operator' => 'in',
    'value' => array(
      'backlit_duratran' => 'backlit_duratran',
      'booklets' => 'booklets',
      'brochures' => 'brochures',
      'business_cards' => 'business_cards',
      'cd_dvd_inserts' => 'cd_dvd_inserts',
      'event_tickets' => 'event_tickets',
      'flyers' => 'flyers',
      'folders' => 'folders',
      'image_slider' => 'image_slider',
      'menus' => 'menus',
      'newsletters' => 'newsletters',
      'postcards' => 'postcards',
      'posters' => 'posters',
      'rack_cards' => 'rack_cards',
      'sell_sheets' => 'sell_sheets',
      'vinyl_banners' => 'vinyl_banners',
      'yard_signs' => 'yard_signs',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'relationship' => 'none',
    'override' => array(
      'button' => 'Use default',
    ),
  ),
  'status' => array(
    'operator' => '=',
    'value' => '1',
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'status',
    'table' => 'node',
    'field' => 'status',
    'relationship' => 'none',
  ),
));
$handler->override_option('row_options', array(
  'image_field' => 'field_slider_image_fid',
  'title_field' => '',
  'link_field' => 'view_node',
));
$handler->override_option('block_description', '');
$handler->override_option('block_caching', -1);

return $views;
}

?>
