<?php

/**
 * @file uc_add_to_cart_block.module
 * Provides blocks for Ubercart product "Add to Cart" and "Buy it Now" forms.
 */

/**
 * Implements hook_block().
 */
function uc_add_to_cart_block_block($op, $delta = 'uc_add_to_cart_block', $edit = array()) {
  switch ($op) {
    case 'list':
      return uc_add_to_cart_block_block_info();
    case 'configure':
      return uc_add_to_cart_block_block_configure($delta);
    case 'save':
      return uc_add_to_cart_block_block_save($delta, $edit);
    case 'view':
      return uc_add_to_cart_block_block_view($delta);
  }
}

/**
 * Provides block information
 * @return array
 */
function uc_add_to_cart_block_block_info() {
  $blocks = array();

  $blocks['uc_add_to_cart_block'] = array(
    'info'       => t('Add product to cart form'),
    'visibility' => 1,
    'pages'      => 'node/*',
    'cache'      => BLOCK_NO_CACHE,
  );

  $blocks['uc_buy_it_now_block'] = array(
    'info'       => t('Buy it now form'),
    'visibility' => 1,
    'pages'      => 'node/*',
    'cache'      => BLOCK_NO_CACHE,
  );

  return $blocks;
}

/**
 * Provides the block configuration form.
 * @param $delta
 *  The block ID to be configured.
 * @return array
 *  An array of form fields/settings used to configure the block.
 */
function uc_add_to_cart_block_block_configure($delta = 'uc_add_to_cart_block') {
  $form = array();

  if ($delta == 'uc_buy_it_now_block') {
    $form['enforce_attribute_selection'] = array(
      '#type' => 'checkbox',
      '#title' => t('Disable attribute validation?'),
      '#default_value' => variable_get('uc_add_to_cart_block_buy_it_now_disable_validation', FALSE),
      '#description' => t('Ubercart validates attribute selection on any add-to-cart function. By disabling this on the buy-it-now function, no attribute validation is performed. This is useful for providing a quick way to put unconfigured products into a cart for quotations.'),
    );
  }

  return $form;
}

/**
 * Saves block settings.
 * @param $delta
 *  The block ID whose settings are to be updated.
 * @param $edit
 *  The array of data holding these block settings.
 */
function uc_add_to_cart_block_block_save($delta = 'uc_add_to_cart_block', $edit = array()) {
  if ($delta == 'uc_buy_it_now_block') {
    variable_set('uc_add_to_cart_block_buy_it_now_disable_validation', $edit['enforce_attribute_selection']);
  }
}

/**
 * Displays the block.
 * @param $delta
 *  The block ID to be displayed.
 */
function uc_add_to_cart_block_block_view($delta = 'uc_add_to_cart_block') {
  // Try to load the product node
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
  }
  else {
    // This probably isn't a node, do nothing.
    return array();
  }

  // If this node isn't a product, do nothing.
  if (!uc_product_is_product($node)) {
    return array();
  }

  // Initialize the $block array to avoid PHP errors.
  $block = array();

  // The subject is displayed at the top of the block.
  $block[$delta]['subject'] = t('Add to Cart');

  switch ($delta) {
    // The full add-to-cart form.
    case 'uc_add_to_cart_block':
      $block[$delta]['content'] = drupal_get_form('uc_product_add_to_cart_form', $node);
    break;

    // The quick-n-dirty 'buy-it-now' button.
    case 'uc_buy_it_now_block':
      $block[$delta]['content'] = drupal_get_form('uc_catalog_buy_it_now_form', $node);
    break;
  }

  return $block[$delta];
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * This function will turn off the attribute validation function if the
 * block settings indicate to do so.
 */
function uc_add_to_cart_block_form_uc_catalog_buy_it_now_form_alter(&$form, &$form_state) {
  // Check if the administrator wants to un-enforce attributes on the buy it now form.
  if (FALSE !== variable_get('uc_add_to_cart_block_buy_it_now_disable_validation', FALSE)) {
    // Remove the 'buy it now' validation function.
    if (FALSE !== ($index = array_search('uc_catalog_buy_it_now_form_validate', $form['#validate']))) {
      unset($form['#validate'][$index]);
    }
  }
}
