<?php
// $Id: uc_price_visibility.module,v 1.2 2010/11/18 16:17:37 joelstein Exp $

/**
 * Implementation of hook_menu().
 */
function uc_price_visibility_menu() {
  $items['admin/store/settings/products/edit/price-visibility'] = array(
    'title' => t('Price visibility'),
    'access arguments' => array('administer store'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('uc_price_visibility_settings'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
    'file' => 'uc_price_visibility.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_nodeapi().
 */
function uc_price_visibility_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $user;

  if (!uc_product_is_product($node->type)) {
    return;
  }

  switch ($op) {
    case 'insert':
    case 'update':
      $roles = implode(',', array_filter($node->uc_price_visibility_roles));
      db_query("DELETE FROM {uc_price_visibility} WHERE nid = %d", $node->nid);
      db_query("INSERT INTO {uc_price_visibility} (nid, roles) VALUES (%d, '%s')", $node->nid, $roles);
      break;

    case 'load':
      $result = db_fetch_array(db_query("SELECT * FROM {uc_price_visibility} WHERE nid = %d", $node->nid));
      // This node's visibility has been set.
      if ($result) {
        // Multiple roles.
        if (strpos($result['roles'], ',') !== FALSE) {
          foreach (explode(',', $result['roles']) as $rid) {
            $roles[$rid] = $rid;
          }
        }
        // One role.
        else {
          $roles[$result['roles']] = $result['roles'];
        }
      }
      // None (use default).
      else {
        $roles = variable_get('uc_price_visibility_roles', array());
      }
      return array('uc_price_visibility' => $roles);
      break;

    case 'view':
      $visible = FALSE;
      foreach (array_keys($node->uc_price_visibility) as $rid) {
        if (isset($user->roles[$rid])) {
          $visible = TRUE;
          break;
        }
      }
      if (!$visible) {
        $message_field = variable_get('uc_price_visibility_message_field', 'sell_price');
        foreach (array('display_price', 'sell_price', 'add_to_cart') as $field) {
          if ($field == $message_field) {
            $node->content[$field]['#value'] = variable_get('uc_price_visibility_message', '');
          }
          else {
            $node->content[$field]['#access'] = FALSE;
          }
        }
      }
      break;

    case 'delete':
      db_query("DELETE FROM {uc_price_visibility} WHERE nid = %d", $node->nid);
      break;
  }
}

/**
 * Implementation of hook_form_alter().
 */
function uc_price_visibility_form_alter(&$form, &$form_state, $form_id) {
  if (uc_product_is_product_form($form)) {
    $form['base']['uc_price_visibility_roles'] = array(
      '#type' => 'checkboxes',
      '#options' => user_roles(),
      '#title' => t("Allow the following roles to view this product's price and add it to the cart"),
      '#description' => t('If none are selected, the product will be visible to all users. If a user has any of the roles checked, the product will be visible to that user.'),
      '#default_value' => isset($form['#node']->uc_price_visibility)
        ? $form['#node']->uc_price_visibility
        : variable_get('uc_price_visibility_roles', array()),
    );
  }
}
